//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is290_project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int AssetID { get; set; }
        public string AssetLocation { get; set; }
        public string AssetName { get; set; }
        public int AssetType { get; set; }
        public int AssetStock { get; set; }
        public decimal AssetPrice { get; set; }
    }
}
